"""Generated IQ export formats."""

from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
import tarfile
import xml.etree.ElementTree as ET

import numpy as np

from pluto_vsg.engine import GenerationResult
from pluto_vsg.model import WaveformProject


_WV_WAVEFORM_OFFSET = 0x4000
_WV_FULL_SCALE = 32767.0


def save_npz(
    path: str | Path, result: GenerationResult, project: WaveformProject
) -> None:
    np.savez_compressed(
        Path(path),
        iq=np.asarray(result.iq, dtype=np.complex64),
        sample_rate_hz=np.float64(result.sample_rate_hz),
        center_frequency_hz=np.float64(project.center_frequency_hz),
        usable_bandwidth_hz=np.float64(result.sample_rate_hz),
        full_scale=np.float64(1.0),
        amplitude_calibrated=np.bool_(False),
        source=np.asarray("Pluto VSG"),
        project_name=np.asarray(project.name),
    )


def _tar_info(name: str, size: int) -> tarfile.TarInfo:
    info = tarfile.TarInfo(name)
    info.size = int(size)
    info.mtime = 0
    info.mode = 0o644
    info.uid = info.gid = 0
    info.uname = info.gname = ""
    return info


def save_iq_tar(
    path: str | Path, result: GenerationResult, project: WaveformProject
) -> None:
    iq = np.asarray(result.iq, dtype=np.complex64)
    interleaved = np.empty(iq.size * 2, dtype="<f4")
    interleaved[0::2] = iq.real
    interleaved[1::2] = iq.imag
    binary = interleaved.tobytes()
    data_filename = "pluto_vsg.complex.1ch.float32"

    root = ET.Element("RS_IQ_TAR_FileFormat", {"fileFormatVersion": "2"})
    ET.SubElement(root, "Name").text = project.name
    ET.SubElement(root, "Comment").text = "Generated by Pluto VSG"
    ET.SubElement(root, "DateTime").text = datetime.now(timezone.utc).isoformat()
    ET.SubElement(root, "Samples").text = str(iq.size)
    ET.SubElement(root, "Clock", {"unit": "Hz"}).text = f"{result.sample_rate_hz:.12g}"
    ET.SubElement(root, "Format").text = "complex"
    ET.SubElement(root, "DataType").text = "float32"
    ET.SubElement(root, "ScalingFactor", {"unit": "V"}).text = "1"
    ET.SubElement(root, "NumberOfChannels").text = "1"
    ET.SubElement(root, "DataFilename").text = data_filename
    user_data = ET.SubElement(root, "UserData")
    rs = ET.SubElement(user_data, "RohdeSchwarz")
    mandatory = ET.SubElement(rs, "DataImportExport_MandatoryData")
    names = ET.SubElement(mandatory, "ChannelNames")
    ET.SubElement(names, "ChannelName").text = "Pluto VSG IQ"
    ET.SubElement(mandatory, "CenterFrequency", {"unit": "Hz"}).text = (
        f"{project.center_frequency_hz:.12g}"
    )
    metadata = ET.SubElement(rs, "PlutoVSG")
    ET.SubElement(metadata, "Standard").text = project.standard.value
    ET.SubElement(metadata, "SamplesPerSymbol").text = str(
        project.samples_per_symbol
    )
    xml = ET.tostring(root, encoding="utf-8", xml_declaration=True)

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(destination, mode="w", format=tarfile.PAX_FORMAT) as archive:
        archive.addfile(_tar_info("pluto_vsg.xml", len(xml)), BytesIO(xml))
        archive.addfile(_tar_info(data_filename, len(binary)), BytesIO(binary))


def _wv_checksum(binary: bytes) -> int:
    """Return the R&S SMU-WV XOR checksum for an IQ data block."""

    if len(binary) % 4:
        raise ValueError("R&S WV waveform data must contain complete I/Q pairs")
    checksum = 0xA50F74FF
    for offset in range(0, len(binary), 4):
        checksum ^= int.from_bytes(binary[offset : offset + 4], "little")
    return checksum & 0xFFFFFFFF


def _wv_empty_tag(prefix_size: int) -> bytes:
    """Build the mandatory placeholder that aligns WAVEFORM to 0x4000."""

    available = _WV_WAVEFORM_OFFSET - prefix_size
    if available <= 0:
        raise ValueError("R&S WV header is too large for the 0x4000 data offset")
    # Length counts '#' plus the blank placeholder bytes, but not the closing
    # brace. Its own decimal digit count therefore participates in the result.
    length = available
    for _ in range(16):
        start = f"{{EMPTYTAG-{length}:#".encode("ascii")
        candidate = available - len(start)
        if candidate == length:
            break
        length = candidate
    else:  # pragma: no cover - the decimal length converges in two iterations
        raise ValueError("Could not construct the R&S WV EMPTYTAG")
    if length < 1:
        raise ValueError("R&S WV header leaves no room for EMPTYTAG data")
    tag = start + (b" " * (length - 1)) + b"}"
    if prefix_size + len(tag) != _WV_WAVEFORM_OFFSET:
        raise ValueError("R&S WV EMPTYTAG alignment is inconsistent")
    return tag


def _wv_ascii_comment(value: str) -> str:
    text = value.encode("ascii", errors="replace").decode("ascii")
    return text.replace("}", ")")[:512]


def save_wv(
    path: str | Path, result: GenerationResult, project: WaveformProject
) -> None:
    """Save normalized complex IQ as an R&S SMU-WV ARB waveform.

    The output follows the tag-oriented WV format documented for the
    R&S SMCV100B. IQ is kept at its generated level; it is not independently
    normalized during export.
    """

    iq = np.asarray(result.iq, dtype=np.complex128).reshape(-1)
    if not iq.size:
        raise ValueError("Cannot export an empty R&S WV waveform")
    if not np.all(np.isfinite(iq)):
        raise ValueError("R&S WV export requires finite IQ samples")
    peak = float(np.max(np.abs(iq)))
    if peak <= 0.0:
        raise ValueError("Cannot export an all-zero R&S WV waveform")
    if peak > 1.0 + 1.0 / _WV_FULL_SCALE:
        raise ValueError(
            "R&S WV export requires normalized IQ with vector magnitude <= 1.0"
        )

    interleaved = np.empty(iq.size * 2, dtype="<i2")
    interleaved[0::2] = np.rint(
        np.clip(iq.real, -1.0, 1.0) * _WV_FULL_SCALE
    ).astype(np.int16)
    interleaved[1::2] = np.rint(
        np.clip(iq.imag, -1.0, 1.0) * _WV_FULL_SCALE
    ).astype(np.int16)
    binary = interleaved.tobytes()

    quantized_iq = (
        interleaved[0::2].astype(np.float64)
        + 1j * interleaved[1::2].astype(np.float64)
    ) / _WV_FULL_SCALE
    quantized_peak = float(np.max(np.abs(quantized_iq)))
    quantized_rms = float(np.sqrt(np.mean(np.abs(quantized_iq) ** 2)))
    rms_offset_db = -20.0 * np.log10(quantized_rms)
    peak_offset_db = -20.0 * np.log10(quantized_peak)
    checksum = _wv_checksum(binary)
    created = datetime.now().strftime("%Y-%m-%d;%H:%M:%S")
    comment = _wv_ascii_comment(f"Generated by Pluto VSG: {project.name}")
    tags = (
        f"{{TYPE: SMU-WV,{checksum}}}"
        f"{{COMMENT: {comment}}}"
        f"{{DATE: {created}}}"
        f"{{SAMPLES: {iq.size}}}"
        f"{{CLOCK: {result.sample_rate_hz:.12g}}}"
        f"{{LEVEL OFFS: {rms_offset_db:.12g},{peak_offset_db:.12g}}}"
    ).encode("ascii")
    empty_tag = _wv_empty_tag(len(tags))
    waveform_length = len(binary) + 1
    waveform_tag = f"{{WAVEFORM-{waveform_length}:#".encode("ascii")

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(tags + empty_tag + waveform_tag + binary + b"}")
