"""Generated IQ export formats."""

from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
import tarfile
import xml.etree.ElementTree as ET

import numpy as np

from pluto_vsg.engine import GenerationResult
from pluto_vsg.model import WaveformProject


def save_npz(
    path: str | Path, result: GenerationResult, project: WaveformProject
) -> None:
    np.savez_compressed(
        Path(path),
        iq=np.asarray(result.iq, dtype=np.complex64),
        sample_rate_hz=np.float64(result.sample_rate_hz),
        center_frequency_hz=np.float64(project.center_frequency_hz),
        usable_bandwidth_hz=np.float64(result.sample_rate_hz),
        full_scale=np.float64(1.0),
        amplitude_calibrated=np.bool_(False),
        source=np.asarray("Pluto VSG"),
        project_name=np.asarray(project.name),
    )


def _tar_info(name: str, size: int) -> tarfile.TarInfo:
    info = tarfile.TarInfo(name)
    info.size = int(size)
    info.mtime = 0
    info.mode = 0o644
    info.uid = info.gid = 0
    info.uname = info.gname = ""
    return info


def save_iq_tar(
    path: str | Path, result: GenerationResult, project: WaveformProject
) -> None:
    iq = np.asarray(result.iq, dtype=np.complex64)
    interleaved = np.empty(iq.size * 2, dtype="<f4")
    interleaved[0::2] = iq.real
    interleaved[1::2] = iq.imag
    binary = interleaved.tobytes()
    data_filename = "pluto_vsg.complex.1ch.float32"

    root = ET.Element("RS_IQ_TAR_FileFormat", {"fileFormatVersion": "2"})
    ET.SubElement(root, "Name").text = project.name
    ET.SubElement(root, "Comment").text = "Generated by Pluto VSG"
    ET.SubElement(root, "DateTime").text = datetime.now(timezone.utc).isoformat()
    ET.SubElement(root, "Samples").text = str(iq.size)
    ET.SubElement(root, "Clock", {"unit": "Hz"}).text = f"{result.sample_rate_hz:.12g}"
    ET.SubElement(root, "Format").text = "complex"
    ET.SubElement(root, "DataType").text = "float32"
    ET.SubElement(root, "ScalingFactor", {"unit": "V"}).text = "1"
    ET.SubElement(root, "NumberOfChannels").text = "1"
    ET.SubElement(root, "DataFilename").text = data_filename
    user_data = ET.SubElement(root, "UserData")
    rs = ET.SubElement(user_data, "RohdeSchwarz")
    mandatory = ET.SubElement(rs, "DataImportExport_MandatoryData")
    names = ET.SubElement(mandatory, "ChannelNames")
    ET.SubElement(names, "ChannelName").text = "Pluto VSG IQ"
    ET.SubElement(mandatory, "CenterFrequency", {"unit": "Hz"}).text = (
        f"{project.center_frequency_hz:.12g}"
    )
    metadata = ET.SubElement(rs, "PlutoVSG")
    ET.SubElement(metadata, "Standard").text = project.standard.value
    ET.SubElement(metadata, "SamplesPerSymbol").text = str(
        project.samples_per_symbol
    )
    xml = ET.tostring(root, encoding="utf-8", xml_declaration=True)

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(destination, mode="w", format=tarfile.PAX_FORMAT) as archive:
        archive.addfile(_tar_info("pluto_vsg.xml", len(xml)), BytesIO(xml))
        archive.addfile(_tar_info(data_filename, len(binary)), BytesIO(binary))
