"""External IEEE Annex G values, not expectations generated by our encoder."""
import json
from pathlib import Path

import numpy as np

from pluto_vsg.engine.wifi_legacy_ofdm import (
    _ifft_symbol, _l_sig_bits, _pilot_polarities, _training_fields,
    bcc_encode, interleave, map_constellation, puncture, scramble,
)
from pluto_vsg.wifi.common import LEGACY_RATES

VECTOR = json.loads((Path(__file__).parents[1] / 'data/fixtures/wifi/ieee_80211a_annex_g.json').read_text())


def complex_values(key):
    a = np.asarray(VECTOR[key])
    return a[:, 0] + 1j * a[:, 1]


def test_ieee_signal_all_stages():
    bits = _l_sig_bits(LEGACY_RATES[36], 100)
    np.testing.assert_array_equal(bits, VECTOR['signal_bits'])
    coded = bcc_encode(bits)
    np.testing.assert_array_equal(coded, VECTOR['signal_coded'])
    permuted = interleave(coded, 48, 1)
    np.testing.assert_array_equal(permuted, VECTOR['signal_interleaved'])
    iq = _ifft_symbol(map_constellation(permuted, 1), 0, 1) * np.sqrt(52) / 64
    np.testing.assert_allclose(np.fft.fftshift(np.fft.fft(iq[16:])), complex_values('signal_bins'), atol=1e-12)
    # Annex G uses 1/64 IFFT and half-weight overlap endpoints. Compare the
    # rectangular symbol interior separately from its optional window.
    np.testing.assert_allclose(iq[1:], complex_values('signal_iq_windowed')[1:80], atol=0.00071)


def test_ieee_data_bits_scrambler_tail_and_puncturing():
    psdu = np.frombuffer(bytes.fromhex(VECTOR['psdu_hex']), dtype=np.uint8)
    bits = np.r_[np.zeros(16,dtype=np.uint8), np.unpackbits(psdu,bitorder='little'), np.zeros(48,dtype=np.uint8)]
    np.testing.assert_array_equal(bits[:144], VECTOR['uncoded_first'])
    np.testing.assert_array_equal(bits[-144:], VECTOR['uncoded_last'])
    np.testing.assert_array_equal(scramble(np.zeros(127,dtype=np.uint8),93), VECTOR['scrambler_sequence'])
    coded_input = scramble(bits,93)
    coded_input[816:822] = 0
    np.testing.assert_array_equal(coded_input[:144], VECTOR['scrambled_first'])
    np.testing.assert_array_equal(coded_input[-144:], VECTOR['scrambled_last'])
    np.testing.assert_array_equal(puncture(bcc_encode(coded_input),'3/4')[:192], VECTOR['punctured_first'])


def test_ieee_data_interleaver_constellation_and_frequency_bins():
    permuted = interleave(np.array(VECTOR['punctured_first'],dtype=np.uint8),192,4)
    np.testing.assert_array_equal(permuted, VECTOR['interleaved_first'])
    symbol = _ifft_symbol(map_constellation(permuted,4),1,1)
    bins = np.fft.fftshift(np.fft.fft(symbol[16:])) * np.sqrt(52) / 64
    np.testing.assert_allclose(bins,complex_values('first_data_bins'),atol=0.00071)


def test_independent_receiver_primitives_against_ieee_bits():
    from pluto_protocol.wifi.non_ht import deinterleave, depuncture, viterbi
    signal = deinterleave(np.array(VECTOR['signal_interleaved']),1)
    np.testing.assert_array_equal(signal,VECTOR['signal_coded'])
    np.testing.assert_array_equal(viterbi(2*signal-1),VECTOR['signal_bits'])
    data = deinterleave(np.array(VECTOR['interleaved_first']),4)
    np.testing.assert_array_equal(data,VECTOR['punctured_first'])
    recovered = viterbi(depuncture(2*data-1,'3/4',144))
    np.testing.assert_array_equal(recovered,VECTOR['scrambled_first'])


def test_ieee_normative_training_and_pilot_sequence():
    stf,ltf = _training_fields(1)
    np.testing.assert_allclose(stf,np.tile(stf[:16],10),atol=1e-14)
    np.testing.assert_allclose(ltf[:32],ltf[64:96],atol=1e-14)
    np.testing.assert_allclose(ltf[32:96],ltf[96:],atol=1e-14)
    stf_bins = np.fft.fft(stf[:64]) * np.sqrt(52) / 64
    # Clause 17.3.3 Equation (6), NOT erroneous Annex G.2 in 1999 printing.
    carriers = [-24,-20,-16,-12,-8,-4,4,8,12,16,20,24]
    expected = np.zeros(64,dtype=complex)
    expected[np.array(carriers)%64] = np.array([1,-1,1,-1,-1,1,-1,-1,1,1,1,1])*(1+1j)*np.sqrt(13/6)
    np.testing.assert_allclose(stf_bins,expected,atol=1e-14)
    np.testing.assert_allclose(np.mean(abs(stf)**2),1,atol=1e-14)
    np.testing.assert_allclose(np.mean(abs(ltf[32:96])**2),1,atol=1e-14)
    np.testing.assert_array_equal(_pilot_polarities(7),[1,1,1,1,-1,-1,-1])


def test_ieee_packet_signal_and_first_data_time_samples():
    from pluto_vsg.engine.wifi_legacy_ofdm import WiFiLegacyOFDMWaveformEngine
    from pluto_vsg.model import WiFiSettings, WiFiPSDUSource
    from pluto_vsg.profiles.wifi import wifi_project
    result = WiFiLegacyOFDMWaveformEngine().generate(wifi_project(WiFiSettings(
        legacy_rate_mbps=36, psdu_source=WiFiPSDUSource.RAW_HEX,
        raw_psdu_hex=VECTOR['psdu_hex'],scrambler_seed=93,oversample_factor=1,packet_period_us=1000)))
    # Use the independently published SIGNAL time samples to recover only
    # the common amplitude scale, then G.22 bins for the DATA time waveform.
    actual = result.iq[321:400]
    expected = complex_values('signal_iq_windowed')[1:80]
    gain = np.vdot(actual,expected)/np.vdot(actual,actual)
    assert abs(gain.imag) < 0.0001
    np.testing.assert_allclose(actual*gain.real,expected,atol=0.0008)
    useful = np.fft.ifft(np.fft.ifftshift(complex_values('first_data_bins')))
    np.testing.assert_allclose(result.iq[400:480]*gain.real,np.r_[useful[-16:],useful],atol=0.0008)
